---
title: "Milestone 5"
author: "Rebecca Xi"
date: "3/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Prepare data 

library(ggplot2)
library(readr)
library(RDS)
library(gganimate)
library(tidyverse)

deaths <- read_csv("raw-data/time_series_19-covid-Deaths.csv") %>% 
  rename(
    "province" = "Province/State" ,
    "country" = "Country/Region",
  ) %>% 
  filter(
    country == "China",
    province == "Hubei"
  ) %>% 
  select(-"Lat", -"Long") %>% 
  pivot_longer(names_to = "date",
               values_to = "deaths",
               cols = -c(province, country)) %>% 
  rename("date" = "date")
saveRDS(deaths, file = "hubei_deaths.RDS")
deaths <- readRDS("hubei_deaths.RDS")

recovered <- read_csv("raw-data/time_series_19-covid-Recovered.csv") %>% 
  rename(
    "province" = "Province/State" ,
    "country" = "Country/Region",
  ) %>% 
  filter(
    country == "China",
    province == "Hubei"
  ) %>% 
  select(-"Lat", -"Long") %>% 
  pivot_longer(names_to = "date",
               values_to = "recovered",
               cols = -c(province, country)) %>% 
  rename("date" = "date")
saveRDS(recovered, file = "hubei_recovered.RDS")
recovered <- readRDS("hubei_recovered.RDS")

confirmed <- read_csv("raw-data/time_series_19-covid-Confirmed.csv") %>% 
  rename(
    "province" = "Province/State" ,
    "country" = "Country/Region",
  ) %>% 
  filter(
    country == "China",
    province == "Hubei"
  ) %>% 
  select(-"Lat", -"Long") %>% 
  pivot_longer(names_to = "date",
               values_to = "confirmed",
               cols = -c(province, country)) %>% 
  rename("date" = "date")
saveRDS(confirmed, file = "hubei_confirmed.RDS")
confirmed <- readRDS("hubei_confirmed.RDS")

hubei <- confirmed %>% 
  inner_join(deaths) %>% 
  inner_join(recovered)
```

```{r graphic, echo=FALSE}

# Create plot 

hubei_plot <- hubei %>% 
  ggplot(aes(x = as.Date(date, "%m/%d/%Y"))) +
    geom_line(aes(y = confirmed, color = "Confirmed")) +
    geom_line(aes(y = deaths, color = "Deaths")) +
    geom_line(aes(y = recovered, color = "Recovered")) +
    transition_reveal(as.Date(date, "%m/%d/%Y")) +
    scale_color_manual(
      "", 
      breaks = c("Confirmed", "Deaths", "Recovered"),
      values = c("black", "darkred", "steelblue")
    ) +
    labs(
      title = "COVID-19 in Hubei, China (as of March 19, 2020)",
      subtitle = "Data provided by JHU CSSE",
      x = "Time",
      y = "Count"
    ) +
    scale_x_date(
      date_breaks = "1 week", 
      date_labels = "%b %d"
    ) +
    theme_gray()
hubei_plot
```

